server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: appOne
        uri: http://localhost:8081/
        predicates:
        - Path=/app1/**
      - id: appTwo
        uri: http://localhost:8082/
        predicates:
        - Path=/app2/**
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    reactor.netty: TRACE
    redisratelimiter: DEBUG

