server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: appOne
        uri: http://localhost:8081/
        predicates:
        - Path=/app1/**
      - id: appTwo
        uri: http://localhost:8082/
        predicates:
        - Path=/app2/**